In [ ]:
np.__version__

'1.26.4'

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
a = np.array(2)
b = np.array([[2, 3], [3, 4]])
print(a.ndim)
print(b.shape)
print(b.size)
#c = np.array

0
(2, 2)
4


In [ ]:
c = np.array([1, 2, 3], ndmin = 5)
print(c)
print(c.ndim)

[[[[[1 2 3]]]]]
5


In [ ]:
a = np.arange(10)
a.size

10

In [ ]:
b = a.reshape(2, 5)

In [ ]:
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
a[0]

0

In [ ]:
b[0]

array([0, 1, 2, 3, 4])

In [ ]:
b[0][1]

1

In [ ]:
b[0][1]

1

numpy.linspace() function:


In [ ]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
arr = np.linspace(0, 10, 5, retstep=True)
type(arr)

tuple

In [ ]:
arr

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)

In [ ]:
arr[1]

2.5

numpy.zeros() and numpy.ones() functions:

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros(5, dtype ='int64')

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros(5, dtype ='int64').dtype

dtype('int64')

In [ ]:
arr = np.ones((2,3), dtype ='int_')

In [ ]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.astype('float')

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr1 = np.array([1, 2, True, False])

In [ ]:
arr1

array([1, 2, 1, 0])

In [ ]:
arr2 = np.array(['a', 'b', 2, 3])

In [ ]:
arr2

array(['a', 'b', '2', '3'], dtype='<U21')

Indexing and slicing NumPy arrays:

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a[1]

2

In [ ]:
a[-1]

4

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
b[1][1]

5

In [ ]:
b[1:][1:]

array([], shape=(0, 3), dtype=int64)

Change the shape with reshape() method:


In [ ]:
a = np.arange(10)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a.shape

(10,)

In [ ]:
b = a.reshape(2,5)
b.shape

(2, 5)

Appending elements, rows and columns to arrays:


In [ ]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.append(a, [[7, 8, 9]], axis = 0)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
c = np.append(a, [[7], [8]], axis = 1)
c

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

Deleting array elements, rows and columns:


In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6]])
np.delete(a, 0)

array([2, 3, 4, 5, 6])

In [ ]:
np.delete(a, (0, 2, 4))

array([2, 4, 6])

##Statistical methods of NumPy arrays:

In [ ]:
a = np.arange(1, 11)

In [ ]:
a.min()

1

In [ ]:
a.max()

10

In [ ]:
a.sum()

55

In [ ]:
a.std()

2.8722813232690143

In [ ]:
a.var()

8.25

In [ ]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [ ]:
y = np.arange(1,10)
y = y.reshape((3,3))
print(y)

In [ ]:
print(y.mean(axis=0))

[4. 5. 6.]


In [ ]:
print(y.mean(axis=1))

[2. 5. 8.]


In [ ]:
np.random.seed(123)
a = np.random.randint(1, 11, size=1000)
a

array([ 3,  3,  7,  2,  4, 10,  7,  2,  1,  2, 10,  1,  1, 10,  4,  5,  1,
        1,  5,  2,  8,  4,  3,  5,  8,  3,  5,  9,  1,  8, 10,  4,  5,  7,
        2,  6,  7,  3,  2,  9,  4,  6,  1,  3,  7,  3,  5,  5,  7,  4,  1,
        7,  5,  8,  7,  8,  2,  6,  8, 10,  3,  5,  9,  2,  3,  2,  2,  4,
        6, 10,  1,  9,  2,  7,  4,  4,  6, 10,  8, 10,  3,  4,  4,  4,  9,
        7, 10,  8,  7,  4, 10,  7,  7,  7,  2,  4,  5,  4,  2,  1,  6,  9,
        7,  9, 10,  2,  1,  4,  2,  4,  5,  8,  7,  2,  5,  4,  4,  8,  7,
        9,  7,  5,  5,  8,  1,  1, 10,  9,  9,  5,  9,  7,  2,  7,  9,  8,
       10,  2,  8,  2,  8, 10,  9,  8,  2,  4,  2,  9,  8,  6,  2,  3,  6,
        3,  3, 10,  4,  3,  7,  8, 10,  2,  4,  9,  4,  8, 10, 10,  4,  4,
        6,  7,  1,  9,  8,  8,  5,  5,  6,  1,  9, 10,  3,  6,  2,  6, 10,
        3,  5,  4,  1,  4,  8,  8,  3,  6,  2,  8,  6, 10,  2,  3,  9,  6,
        1, 10,  4,  4,  4,  2,  8,  7,  4,  2,  8,  3,  7,  6, 10,  9, 10,
        5,  8,  9,  6, 10

In [ ]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.median(a)

5.0

In [ ]:
a.sum()

5485

In [ ]:
np.sum(a)

5485

Array Transposition

In [ ]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])